[package]
name = "bevy-chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Set the default for dependencies.
[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.5.0"
bevy_mod_picking = "0.4.0"